import js from '@eslint/js';
import globals from 'globals';

// All cross-file symbols shared between source files via Makefile concatenation.
// Generated from top-level const/let/var/function declarations across all source files.
const projectGlobals = {
    // variables.js
    defaultTopicCount: 'readonly', maxMessageByPage: 'readonly', entitySubject: 'readonly', entityAuthor: 'readonly',
    entityTopicId: 'readonly', jvarchiveUrl: 'readonly', avatarUseJvArchiveApi: 'readonly', deboucledRepositoryUrl: 'readonly',
    deboucledBackendUrl: 'readonly', deboucledApiUrl: 'readonly', apiChangelogUrl: 'readonly', apiYoutubeBlacklistUrl: 'readonly',
    apiPrebouclesDataUrl: 'readonly', apiAiLoopsDataUrl: 'readonly', apiAiBoucledAuthorsDataUrl: 'readonly',
    apiCheckUpdateUrl: 'readonly', apiUpdateUserUrl: 'readonly', apiDiagnosticUrl: 'readonly', apiMessageQuoteUrl: 'readonly',
    checkUpdateExpire: 'readonly', checkUpdateDeferredExpire: 'readonly', youtubeBlacklistRefreshExpire: 'readonly',
    prebouclesRefreshExpire: 'readonly', aiLoopsRefreshExpire: 'readonly', aiBoucledAuthorsRefreshExpire: 'readonly',
    updateUserExpire: 'readonly', diagnosticExpire: 'readonly', hotTopicsRefreshExpire: 'readonly',
    messageQuotesRefreshExpire: 'readonly', pendingMessageQuoteExpire: 'readonly', imageRootUrl: 'readonly',
    avatarSmallSizeRoute: 'readonly', defaultAvatarUrl: 'readonly',
    subjectBlacklistArray: 'writable', authorBlacklistArray: 'writable', topicIdBlacklistMap: 'writable',
    subjectsBlacklistReg: 'writable', authorsBlacklistReg: 'writable', userSubjectBlacklistReg: 'writable',
    userAuthorBlacklistReg: 'writable', topicIdWhitelistArray: 'writable', shadowent: 'writable',
    youtubeBlacklistArray: 'writable', youtubeBlacklistReg: 'writable', aiLoopData: 'writable',
    aiLoopSubjectReg: 'writable', aiLoopAuthorReg: 'writable', aiBoucledAuthorsData: 'writable',
    aiBoucledAuthorsReg: 'writable', hotTopicsData: 'writable', messageQuotesPendingArray: 'writable',
    messageQuotesData: 'writable', jvChatActive: 'writable', pocTopicMap: 'writable', topicAuthorMap: 'writable',
    authorAvatarMap: 'writable', topicFilteredAuthorMap: 'writable', entityBlacklistMatches: 'writable',
    decensuredUsersSet: 'writable', hiddenTotalTopics: 'writable', hiddenSubjects: 'writable',
    hiddenTopicsIds: 'writable', hiddenMessages: 'writable', hiddenAuthors: 'writable',
    hiddenPrivateMessages: 'writable', hiddenSpammers: 'writable', hiddenAuthorArray: 'writable',
    deboucledTopicStatsMap: 'writable', preBoucleArray: 'writable', preBoucleSubjectEnabledArray: 'writable',
    preBoucleAuthorEnabledArray: 'writable', vinzBoucleArray: 'writable', vinzBoucleMessageArray: 'writable',
    matchedSubjects: 'writable', matchedAuthors: 'writable', matchedTopics: 'writable',
    stopHighlightModeratedTopics: 'writable', moderatedTopics: 'writable', sortModeSubject: 'writable',
    sortModeAuthor: 'writable', sortModeTopicId: 'writable', disabledFilteringForumSet: 'writable',
    firstLaunch: 'writable', userId: 'writable', userPseudo: 'writable', currentTopicId: 'writable',
    currentTopicPageId: 'writable', currentTopicAuthor: 'writable', currentForumId: 'writable',
    forumFilteringIsDisabled: 'writable', fetchedChangelog: 'writable', settingsLoaded: 'writable',
    domParser: 'readonly', regexCache: 'readonly', smileyGifMap: 'writable', brokenSmileyGifArray: 'writable',
    smileyGifRegex: 'writable', deboucledPseudos: 'readonly', deboucledTopics: 'readonly',
    decensuredBackendUrl: 'readonly', decensuredApiUrl: 'readonly', apiDecensuredMessagesUrl: 'readonly',
    apiDecensuredSingleMessageUrl: 'readonly', apiDecensuredUsersUrl: 'readonly',
    apiDecensuredCreateMessageUrl: 'readonly', apiDecensuredCreateTopicUrl: 'readonly',
    apiDecensuredTopicByIdUrl: 'readonly', apiDecensuredTopicsByIdsUrl: 'readonly',
    apiDecensuredTopicsPaginatedUrl: 'readonly', apiDecensuredLatestMessagesUrl: 'readonly',
    apiDecensuredStatsUrl: 'readonly', apiDecensuredUsersOnlineUrl: 'readonly',
    apiDecensuredChatStreamUrl: 'readonly', apiDecensuredChatMessageUrl: 'readonly',
    apiDecensuredChatMessagesUrl: 'readonly', apiDecensuredChatTypingStartUrl: 'readonly',
    apiDecensuredChatTypingStopUrl: 'readonly',

    // storage.js constants
    store: 'readonly', TTL_CONFIG: 'readonly',
    localstorage_pocTopics: 'readonly', localstorage_topicAuthors: 'readonly',
    localstorage_authorAvatars: 'readonly', localstorage_topicFilteredAuthors: 'readonly',
    localstorage_pendingMessageQuotes: 'readonly', localstorage_decensuredTopics: 'readonly',
    localstorage_decensuredMessages: 'readonly', localstorage_decensuredSingleMessages: 'readonly',
    localstorage_decensuredUsers: 'readonly',
    // storage_* keys (all readonly)
    storage_init: 'readonly', storage_init_default: 'readonly',
    storage_secret_displayed: 'readonly', storage_secret_displayed_default: 'readonly',
    storage_announcement_displayed: 'readonly', storage_announcement_displayed_default: 'readonly',
    storage_userId: 'readonly', storage_userId_default: 'readonly',
    storage_lastUsedPseudo: 'readonly', storage_lastUsedPseudo_default: 'readonly',
    storage_preBoucles: 'readonly', storage_preBoucles_default: 'readonly',
    storage_blacklistedTopicIds: 'readonly', storage_blacklistedTopicIds_default: 'readonly',
    storage_blacklistedSubjects: 'readonly', storage_blacklistedSubjects_default: 'readonly',
    storage_blacklistedAuthors: 'readonly', storage_blacklistedAuthors_default: 'readonly',
    storage_blacklistedShadows: 'readonly', storage_blacklistedShadows_default: 'readonly',
    storage_whitelistedTopicIds: 'readonly', storage_whitelistedTopicIds_default: 'readonly',
    storage_optionEnableJvRespawnRefinedTheme: 'readonly', storage_optionEnableJvRespawnRefinedTheme_default: 'readonly',
    storage_optionEnableDeboucledDarkTheme: 'readonly', storage_optionEnableDeboucledDarkTheme_default: 'readonly',
    storage_optionBoucledUseJvarchive: 'readonly', storage_optionBoucledUseJvarchive_default: 'readonly',
    storage_optionHideMessages: 'readonly', storage_optionHideMessages_default: 'readonly',
    storage_optionAllowDisplayThreshold: 'readonly', storage_optionAllowDisplayThreshold_default: 'readonly',
    storage_optionDisplayThreshold: 'readonly', storage_optionDisplayThreshold_default: 'readonly',
    storage_optionDisplayBlacklistTopicButton: 'readonly', storage_optionDisplayBlacklistTopicButton_default: 'readonly',
    storage_optionShowJvcBlacklistButton: 'readonly', storage_optionShowJvcBlacklistButton_default: 'readonly',
    storage_optionFilterResearch: 'readonly', storage_optionFilterResearch_default: 'readonly',
    storage_optionDetectPocMode: 'readonly', storage_optionDetectPocMode_default: 'readonly',
    storage_optionPrevisualizeTopic: 'readonly', storage_optionPrevisualizeTopic_default: 'readonly',
    storage_optionDisplayBlackTopic: 'readonly', storage_optionDisplayBlackTopic_default: 'readonly',
    storage_optionDisplayTopicCharts: 'readonly', storage_optionDisplayTopicCharts_default: 'readonly',
    storage_optionDisplayTopicMatches: 'readonly', storage_optionDisplayTopicMatches_default: 'readonly',
    storage_optionClickToShowTopicMatches: 'readonly', storage_optionClickToShowTopicMatches_default: 'readonly',
    storage_optionRemoveUselessTags: 'readonly', storage_optionRemoveUselessTags_default: 'readonly',
    storage_optionMaxTopicCount: 'readonly', storage_optionMaxTopicCount_default: 'readonly',
    storage_optionAntiVinz: 'readonly', storage_optionAntiVinz_default: 'readonly',
    storage_optionBlAuthorIgnoreMp: 'readonly', storage_optionBlAuthorIgnoreMp_default: 'readonly',
    storage_optionBlSubjectIgnoreMessages: 'readonly', storage_optionBlSubjectIgnoreMessages_default: 'readonly',
    storage_optionEnableTopicMsgCountThreshold: 'readonly', storage_optionEnableTopicMsgCountThreshold_default: 'readonly',
    storage_optionTopicMsgCountThreshold: 'readonly', storage_optionTopicMsgCountThreshold_default: 'readonly',
    storage_optionReplaceResolvedPicto: 'readonly', storage_optionReplaceResolvedPicto_default: 'readonly',
    storage_optionDisplayTopicIgnoredCount: 'readonly', storage_optionDisplayTopicIgnoredCount_default: 'readonly',
    storage_optionEnhanceQuotations: 'readonly', storage_optionEnhanceQuotations_default: 'readonly',
    storage_optionAntiSpam: 'readonly', storage_optionAntiSpam_default: 'readonly',
    storage_optionSmoothScroll: 'readonly', storage_optionSmoothScroll_default: 'readonly',
    storage_optionAntiLoopAiMode: 'readonly', storage_optionAntiLoopAiMode_default: 'readonly',
    storage_optionDisplayHotTopics: 'readonly', storage_optionDisplayHotTopics_default: 'readonly',
    storage_optionHideLongMessages: 'readonly', storage_optionHideLongMessages_default: 'readonly',
    storage_optionDisplayTitleSmileys: 'readonly', storage_optionDisplayTitleSmileys_default: 'readonly',
    storage_optionDisplayTopicAvatar: 'readonly', storage_optionDisplayTopicAvatar_default: 'readonly',
    storage_optionHideAvatarBorder: 'readonly', storage_optionHideAvatarBorder_default: 'readonly',
    storage_optionEmbedVideos: 'readonly', storage_optionEmbedVideos_default: 'readonly',
    storage_optionEmbedTwitter: 'readonly', storage_optionEmbedTwitter_default: 'readonly',
    storage_optionDisplayBadges: 'readonly', storage_optionDisplayBadges_default: 'readonly',
    storage_optionGetMessageQuotes: 'readonly', storage_optionGetMessageQuotes_default: 'readonly',
    storage_optionFilterHotTopics: 'readonly', storage_optionFilterHotTopics_default: 'readonly',
    storage_optionEnableDecensured: 'readonly', storage_optionEnableDecensured_default: 'readonly',
    storage_optionEnableDecensuredBadges: 'readonly', storage_optionEnableDecensuredBadges_default: 'readonly',
    storage_optionAutoDecryptMessages: 'readonly', storage_optionAutoDecryptMessages_default: 'readonly',
    storage_optionDisplayDecensuredUsersCount: 'readonly', storage_optionDisplayDecensuredUsersCount_default: 'readonly',
    storage_optionEnableDecensuredTopics: 'readonly', storage_optionEnableDecensuredTopics_default: 'readonly',
    storage_optionDisplayDecensuredWidget: 'readonly', storage_optionDisplayDecensuredWidget_default: 'readonly',
    storage_optionEnableDecensuredChat: 'readonly', storage_optionEnableDecensuredChat_default: 'readonly',
    storage_decensuredLastPing: 'readonly', storage_deboucled_decensuredPingFailures: 'readonly',
    storage_decensuredLastStatsLoad: 'readonly', storage_decensuredOnlineCount: 'readonly',
    storage_pendingDecensuredTopic: 'readonly', storage_pendingDecensuredTopic_default: 'readonly',
    storage_disabledFilteringForums: 'readonly', storage_disabledFilteringForums_default: 'readonly',
    storage_totalHiddenTopicIds: 'readonly', storage_totalHiddenSubjects: 'readonly',
    storage_totalHiddenAuthors: 'readonly', storage_totalHiddenMessages: 'readonly',
    storage_totalHiddenPrivateMessages: 'readonly', storage_totalHiddenSpammers: 'readonly',
    storage_TopicStats: 'readonly', storage_lastUpdateCheck: 'readonly', storage_lastUpdateDeferredCheck: 'readonly',
    storage_youtubeBlacklist: 'readonly', storage_youtubeBlacklist_default: 'readonly',
    storage_youtubeBlacklistLastUpdate: 'readonly',
    storage_preBouclesData: 'readonly', storage_preBouclesData_default: 'readonly', storage_prebouclesLastUpdate: 'readonly',
    storage_aiLoopsData: 'readonly', storage_aiLoopsData_default: 'readonly', storage_aiLoopsLastUpdate: 'readonly',
    storage_aiBoucledAuthorsData: 'readonly', storage_aiBoucledAuthorsData_default: 'readonly',
    storage_aiBoucledAuthorsLastUpdate: 'readonly',
    storage_lastUpdateUser: 'readonly', storage_DiagnosticLastUpdate: 'readonly',
    storage_hotTopicsData: 'readonly', storage_hotTopicsData_default: 'readonly', storage_hotTopicsLastUpdate: 'readonly',
    storage_messageQuotesData: 'readonly', storage_messageQuotesData_default: 'readonly',
    storage_messageQuotesLastUpdate: 'readonly',
    storage_Keys: 'readonly', storage_excluded_user_Keys: 'readonly', storage_Keys_Blacklists: 'readonly',

    // jvarchiveapi.js
    jvarchiveApiUrl: 'readonly', jvarchiveApiTopicsUrl: 'readonly', jvarchiveApiAuteursUrl: 'readonly',
    jvarchiveMessagesUrl: 'readonly', jvarchiveApiStatsUrl: 'readonly',
    jvarchiveApiGetHotTopicsRoute: 'readonly', jvarchiveApiGetAuthorRoute: 'readonly',
    jvarchiveApiGetAuthorLastMessagesRoute: 'readonly', jvarchiveApiGetAuthorLastTopicsRoute: 'readonly',
    jvarchiveApiGetMessageRoute: 'readonly', jvarchiveApiGetDeletedStatsRoute: 'readonly',
    getJvArchiveHotTopics: 'readonly', getJvArchiveAuthor: 'readonly', getJvArchiveAuthorLastMessages: 'readonly',
    getJvArchiveAuthorLastTopics: 'readonly', getJvArchiveMessage: 'readonly', getJvArchiveDeletedStats: 'readonly',
    jvArchiveTop1Url: 'readonly', jvArchiveTop2Url: 'readonly', jvArchiveTop3Url: 'readonly',
    jvArchiveMedalSvg: 'readonly',

    // decensured-variables.js
    decensuredInitialized: 'writable', decensuredPingTimer: 'writable', decensuredUsersTimer: 'writable',
    decensuredUsersLoading: 'writable', tabOrderSetupInProgress: 'writable', isProcessingTopicCreation: 'writable',
    messageElementsCache: 'writable', messageElementsCacheTime: 'writable', decensuredFormObserver: 'writable',
    platitudeTopicSequenceData: 'writable', platitudeMessageSequenceData: 'writable',
    topicWithMessagesIndexSequences: 'writable', sequencesInitialized: 'writable',
    decensuredIsBuilding: 'writable', decensuredTopicMessagesUseCache: 'writable',
    decensuredTopicMessagesCache: 'writable', domCache: 'writable',
    debouncedHighlightDecensuredTopics: 'writable', debouncedLoadFloatingWidgetTopics: 'writable',
    throttledDecryptTopicMessages: 'writable', throttledSetupTabOrder: 'writable',
    throttledClearDomCache: 'writable', throttledHighlightDecensuredTopics: 'writable',
    topicDecensuredState: 'writable', DECENSURED_CONFIG: 'readonly',
    platitudeMessages: 'readonly', platitudeTopics: 'readonly', stickers: 'readonly',

    // decensured-chat.js
    decensuredChatInstance: 'writable', DecensuredChat: 'readonly',

    // decensured-widget.js
    _topicsUnreadCount: 'writable', _messagesUnreadCount: 'writable',

    // All cross-file functions (readonly)
    // helpers.js
    normalizeDiacritic: 'readonly', normalizeCompatibility: 'readonly', removeSurrogatePairs: 'readonly',
    escapeRegexPatterns: 'readonly', handleGenericChar: 'readonly', capitalize: 'readonly',
    removeDoubleSpaces: 'readonly', isMatch: 'readonly', sortNormalize: 'readonly', hasAny: 'readonly',
    mapAnyValue: 'readonly', mapAddIncrement: 'readonly', mapAddArrayIncrement: 'readonly',
    mapSortByValueThenKey: 'readonly', mergeArrays: 'readonly', normalizeValue: 'readonly',
    buildEntityRegex: 'readonly', buildArrayRegex: 'readonly', invalidateRegexCache: 'readonly',
    insertAfter: 'readonly', plural: 'readonly', preferDarkTheme: 'readonly', addStyles: 'readonly',
    addSvg: 'readonly', decryptJvCare: 'readonly', sleep: 'readonly', group: 'readonly', groupBy: 'readonly',
    removeRepeatingCharacters: 'readonly', replaceNumbersSimilarToCharacters: 'readonly',
    calcStringDistanceScore: 'readonly', awaitElements: 'readonly', getWordBoundsAtPosition: 'readonly',
    getCaretCoordinates: 'readonly', getTextChildren: 'readonly', fetchHtml: 'readonly',
    fetchJson: 'readonly', fetchJsonWithParams: 'readonly', fetchWithTimeout: 'readonly',
    formatDateToFrenchFormat: 'readonly', getUUIDv4: 'readonly', dateIsToday: 'readonly',
    stringifyError: 'readonly', buildRandomStr: 'readonly', prependEvent: 'readonly',
    setTextAreaValue: 'readonly', formatTimeAgo: 'readonly', escapeHtml: 'readonly',
    // storage.js
    initLocalForageTTL: 'readonly', getBlacklistWithKey: 'readonly', initUserId: 'readonly',
    initStorage: 'readonly', loadStorage: 'readonly', saveStorage: 'readonly',
    loadLocalStorage: 'readonly', saveLocalStorage: 'readonly', getTTLInfo: 'readonly',
    cleanupExpiredData: 'readonly', refreshApiData: 'readonly', loadPreBouclesStatuses: 'readonly',
    togglePreBoucleStatus: 'readonly', savePreBouclesStatuses: 'readonly',
    addEntityBlacklist: 'readonly', removeEntityBlacklist: 'readonly', removeTopicIdBlacklist: 'readonly',
    storageIncrement: 'readonly', saveTotalHidden: 'readonly', getStorageJson: 'readonly',
    backupStorage: 'readonly', restoreStorage: 'readonly', showRestoreCompleted: 'readonly',
    loadFile: 'readonly', importFromTotalBlacklist: 'readonly', buildBlacklistsRegex: 'readonly',
    // header.js
    buildHeaderNotifQuotes: 'readonly', getHeaderNotifQuotesCount: 'readonly',
    setHeaderNotifQuotesCount: 'readonly', buildHeaderNotif: 'readonly',
    buildQuoteNotifications: 'readonly', markReadAllQuoteNotifications: 'readonly', markQuoteNotifRead: 'readonly',
    // preboucles.js
    loadPreboucleArrayCache: 'readonly', loadPreBoucleRegexCache: 'readonly',
    isEntityInPreboucles: 'readonly', makeVinzSubjectPure: 'readonly',
    initVinzBoucles: 'readonly', initShadowent: 'readonly',
    // apidata.js
    mustRefresh: 'readonly', queryApiData: 'readonly', queryHotTopics: 'readonly',
    checkUpdate: 'readonly', updateUser: 'readonly', sendDiagnostic: 'readonly',
    sendMessageQuote: 'readonly', updateMessageQuote: 'readonly',
    parseYoutubeBlacklistData: 'readonly', parsePreboucleData: 'readonly',
    parseAiLoopData: 'readonly', parseAiBoucledAuthorsData: 'readonly',
    parseHotTopicsData: 'readonly', parseMessageQuotesData: 'readonly',
    // jvarchiveapi.js
    parseJvArchiveHotTopicResults: 'readonly', parseJvArchiveAuthorResult: 'readonly',
    parseJvArchiveAuthorLastMessageResults: 'readonly', parseJvArchiveTopicsResults: 'readonly',
    parseJvArchiveDeletedStatsResults: 'readonly',
    // stats.js
    addRightBlocMatches: 'readonly', addRightBlocStats: 'readonly', buildStatsChart: 'readonly',
    buildChartIframe: 'readonly', updateTopicHiddenAtDate: 'readonly', addRightBlocHotTopics: 'readonly',
    // topics.js
    getAllTopics: 'readonly', fillTopics: 'readonly', createTopicListOverlay: 'readonly',
    toggleTopicOverlay: 'readonly', addTopicIdBlacklist: 'readonly', getTopicTitle: 'readonly',
    getCurrentTopicId: 'readonly', getTopicId: 'readonly', getTopicCurrentPageId: 'readonly',
    getTopicPageIdFromUri: 'readonly', getTopicLastPageId: 'readonly', updateTopicsHeader: 'readonly',
    removeTopic: 'readonly', removeSiblingMessages: 'readonly', addTopic: 'readonly', topicExists: 'readonly',
    getTopicMessageCount: 'readonly', getTopicLoop: 'readonly', handleAntiLoopAi: 'readonly',
    isTopicBlacklisted: 'readonly', filterMatchResults: 'readonly',
    getSubjectBlacklistMatches: 'readonly', getAuthorBlacklistMatches: 'readonly',
    isContentYoutubeBlacklisted: 'readonly', isVinzTopic: 'readonly',
    getTopicPocStatus: 'readonly', isTopicPoC: 'readonly', buildBadge: 'readonly',
    addBadgeTag: 'readonly', markTopicPoc: 'readonly', markTopicLoop: 'readonly',
    markAuthorLoop: 'readonly', markTopicHot: 'readonly', buildBadgeContainer: 'readonly',
    buildAuthorBlacklistBadges: 'readonly', addIgnoreButtons: 'readonly',
    addPrevisualizeTopicEvent: 'readonly', handleTopicPictos: 'readonly',
    topicIsModerated: 'readonly', removeUselessTags: 'readonly', handleTopicAvatars: 'readonly',
    createTopicTitleSmileys: 'readonly', buildLoaderStatus: 'readonly', buildFloatingNavbar: 'readonly',
    toggleInfiniteScroll: 'readonly', createSmoothScroll: 'readonly',
    buildEnableSmoothScrollButton: 'readonly', buildHotTopics: 'readonly', isHotTopic: 'readonly',
    initSmileyGifMap: 'readonly', buildSmileyUrl: 'readonly', getSmileyImgHtml: 'readonly',
    // messages.js
    getAllMessages: 'readonly', buildMessagesHeader: 'readonly', updateMessagesHeader: 'readonly',
    removeMessage: 'readonly', buildDeboucledBlacklistButton: 'readonly',
    upgradeJvcBlacklistButton: 'readonly', addAuthorButtons: 'readonly', buildAuthorBadges: 'readonly',
    handleJvChatAndTopicLive: 'readonly', handleLiveDecensuredMessage: 'readonly',
    enableJvChatAndTopicLiveEvents: 'readonly', getParagraphChildren: 'readonly',
    getMessageContentWithoutQuotes: 'readonly', buildNoelshackMiniUrl: 'readonly',
    buildNoelshackDirectUrl: 'readonly', fixMessageUrls: 'readonly',
    embedTwitterLinks: 'readonly', embedVocaroo: 'readonly', embedZupimages: 'readonly',
    embedVideos: 'readonly', embedYoutube: 'readonly', handleLongMessages: 'readonly',
    handleQuotedAuthorBlacklist: 'readonly', findQuotedMessagesFromContent: 'readonly',
    highlightQuotedAuthor: 'readonly', handleMessageAssignTopicAuthor: 'readonly',
    highlightSpecialAuthors: 'readonly', fixMessageJvCare: 'readonly',
    enhanceBlockquotes: 'readonly', getLocationMessageId: 'readonly', setHdAvatars: 'readonly',
    // postmessage.js
    getAuthorFromMessageElem: 'readonly', getDateFromMessageElem: 'readonly',
    getRawTypedMessage: 'readonly', prepareMessageQuoteInfo: 'readonly',
    fixNoelshackDirectUrl: 'readonly', handlePostMessage: 'readonly',
    bypassTextCensorship: 'readonly', validatePendingMessageQuotes: 'readonly',
    cleanupPendingMessageQuotes: 'readonly', postNewMessage: 'readonly',
    buildQuoteMessage: 'readonly', suggestAuthors: 'readonly', getTextSelection: 'readonly',
    getSelectionOffset: 'readonly', addMessagePartialQuoteEvents: 'readonly',
    addMessageQuoteEvents: 'readonly', addAuthorSuggestionEvent: 'readonly',
    // decensured-helpers.js
    getCachedElement: 'readonly', debounce: 'readonly', throttle: 'readonly', clearDomCache: 'readonly',
    getRandomSticker: 'readonly', addStickerToMessage: 'readonly', getRandomPlatitudeMessage: 'readonly',
    getRandomPlatitudeTitle: 'readonly', createShuffledSequence: 'readonly', getNextIndexFromSequence: 'readonly',
    initAllSequences: 'readonly', initAllPlatitudeSequences: 'readonly',
    getRandomTopicWithMessage: 'readonly', getRandomMessageForTitle: 'readonly',
    findElement: 'readonly', cleanupTimers: 'readonly', logDecensuredError: 'readonly',
    addAlertbox: 'readonly', fetchDecensuredApi: 'readonly',
    // decensured-api.js
    getCachedDecensuredTopics: 'readonly', setCachedDecensuredTopic: 'readonly',
    getCachedDecensuredMessages: 'readonly', setCachedDecensuredMessages: 'readonly',
    getCachedDecensuredSingleMessage: 'readonly', setCachedDecensuredSingleMessage: 'readonly',
    invalidateDecensuredTopicCache: 'readonly', pingDecensuredApi: 'readonly',
    createDecensuredMessage: 'readonly', getDecensuredMessages: 'readonly',
    createDecensuredTopic: 'readonly', createDecensuredTopicMessage: 'readonly',
    getDecensuredTopic: 'readonly', getDecensuredTopicsBatch: 'readonly',
    getDecensuredSingleMessage: 'readonly', decryptSingleMessage: 'readonly',
    showDecensuredUsersModal: 'readonly', loadDecensuredStatsData: 'readonly',
    getDecensuredTopicsPaginated: 'readonly', getDecensuredLatestMessages: 'readonly',
    checkDecensuredUsers: 'readonly', sendChatMessage: 'readonly', getChatMessages: 'readonly',
    createChatEventSource: 'readonly', sendTypingStart: 'readonly', sendTypingStop: 'readonly',
    // decensured-formatting.js
    formatSpoilers: 'readonly', formatCodeBlocks: 'readonly', formatInlineCode: 'readonly',
    formatJvcBold: 'readonly', formatJvcItalic: 'readonly', formatJvcUnderline: 'readonly',
    formatJvcStrikethrough: 'readonly', formatJvcCode: 'readonly', formatJvcSpoiler: 'readonly',
    formatJvcLists: 'readonly', formatJvcBlockquotes: 'readonly', formatBoldAndItalicText: 'readonly',
    formatStrikethrough: 'readonly', formatNoelshackImages: 'readonly', formatRisibankImages: 'readonly',
    formatZupimagesImages: 'readonly', formatImages: 'readonly', formatLinks: 'readonly',
    formatSmileys: 'readonly', processParagraphContent: 'readonly', cleanupContent: 'readonly',
    formatParagraphs: 'readonly', formatMessageContent: 'readonly',
    highlightChatMentions: 'readonly', formatChatMessageContent: 'readonly',
    initializeSpoilerHandlers: 'readonly',
    // decensured-topics.js
    isTopicsDecensuredEnabled: 'readonly', extractTopicIdFromUrl: 'readonly',
    isValidTopicId: 'readonly', updateTopicTitle: 'readonly',
    addTopicDecensuredIndicator: 'readonly', formatTopicAsDecensured: 'readonly',
    checkAndProcessNewTopic: 'readonly', applyDecensuredFormattingToNewTopic: 'readonly',
    verifyCurrentTopicDecensured: 'readonly', replaceTopicPostButtonWithDecensured: 'readonly',
    restoreOriginalTopicPostButton: 'readonly', extractTitleFromElement: 'readonly',
    getTitleFromTopicPage: 'readonly', cleanTopicUrl: 'readonly',
    preloadDecensuredTopicsStatus: 'readonly', markTopicAsDecensured: 'readonly',
    // decensured-messages.js
    getMessageElements: 'readonly', processContent: 'readonly', processDecensuredMessage: 'readonly',
    decryptMessages: 'readonly', addDecensuredBadgesToAllMessages: 'readonly',
    decryptTopicMessages: 'readonly', handleDecensuredQuote: 'readonly',
    extractMessageIdFromUrl: 'readonly', getCurrentMessageIdFromUrl: 'readonly',
    removeReportButton: 'readonly', invalidateMessageElementsCache: 'readonly',
    processJvChatDecensuredMessage: 'readonly', addJvChatDecensuredBadge: 'readonly',
    handleJvChatDecensuredQuote: 'readonly', getCurrentMessageContent: 'readonly',
    createMessageIndex: 'readonly', getMessageId: 'readonly',
    // decensured-ui.js
    buildDecensuredBadge: 'readonly', setupThemeToggleListener: 'readonly',
    buildDecensuredMessagesUI: 'readonly', setupTabOrder: 'readonly',
    setupMessageFormTabOrder: 'readonly', setupTopicFormTabOrder: 'readonly',
    addDecensuredBadge: 'readonly', addUXHints: 'readonly', cleanupTopicDecensuredState: 'readonly',
    getTopicFormElements: 'readonly', buildDecensuredTopicsUI: 'readonly',
    injectDecensuredTopicUI: 'readonly', reorderTopicFormElements: 'readonly',
    getMessageTextarea: 'readonly', replacePostButtonWithDecensured: 'readonly',
    restoreOriginalPostButton: 'readonly', highlightDecensuredTopics: 'readonly',
    setupDynamicTopicHighlighting: 'readonly', setupTopicTextareaForDecensured: 'readonly',
    restoreTopicTextareaFromDecensured: 'readonly', setupTopicTitleInputForDecensured: 'readonly',
    restoreTopicTitleInputFromDecensured: 'readonly', activateDecensuredMode: 'readonly',
    animateContentTransition: 'readonly', animateTopicTitleTransition: 'readonly',
    createToggleButton: 'readonly', setupFormElementsObserver: 'readonly',
    cleanupFormObserver: 'readonly', createDecensuredContainer: 'readonly',
    createTopicTitleContainers: 'readonly', moveMainTextareaToContainer: 'readonly',
    getElementSelector: 'readonly', restoreMainTextareaFromContainer: 'readonly',
    setupToggleHandlers: 'readonly',
    // decensured-users.js
    createDecensuredUsersHeader: 'readonly', createAndShowUsersModal: 'readonly',
    toggleDecensuredUsersCountDisplay: 'readonly', startDecensuredUsersMonitoring: 'readonly',
    updateDecensuredStatsOnlineCount: 'readonly', toggleDecensuredBadgesDisplay: 'readonly',
    // decensured-chat.js
    initializeDecensuredChat: 'readonly', getDecensuredChatInstance: 'readonly',
    destroyDecensuredChat: 'readonly',
    // decensured-widget.js
    createDecensuredFloatingWidget: 'readonly', setupFloatingWidgetEvents: 'readonly',
    setupWidgetTabs: 'readonly', createFloatingWidgetOverlay: 'readonly',
    updateFloatingWidgetTheme: 'readonly', showFloatingWidget: 'readonly',
    hideFloatingWidget: 'readonly', loadFloatingWidgetTopics: 'readonly',
    initializeFloatingWidgetInfiniteScroll: 'readonly', appendTopicsToContainer: 'readonly',
    createTopicElement: 'readonly', showEmptyState: 'readonly', showErrorState: 'readonly',
    loadFloatingWidgetMessages: 'readonly', initializeFloatingWidgetMessagesScroll: 'readonly',
    appendMessagesToContainer: 'readonly', cleanMessagePreview: 'readonly',
    createMessageElement: 'readonly', truncateText: 'readonly',
    showEmptyMessagesState: 'readonly', showErrorMessagesState: 'readonly',
    startFloatingWidgetMonitoring: 'readonly', handleNewTopicNotification: 'readonly',
    handleNewMessageDecensuredNotification: 'readonly', updateWidgetTabBadge: 'readonly',
    clearWidgetTabBadge: 'readonly', updateWidgetLanguetteBadge: 'readonly',
    toggleDecensuredFloatingWidget: 'readonly', updateChatStatusWhenDisabled: 'readonly',
    updateChatStatusWhenNotAuthenticated: 'readonly',
    // decensured-posting.js
    setFormDisabled: 'readonly', handleDecensuredPost: 'readonly', buildFormData: 'readonly',
    buildMultipartBody: 'readonly', submitForm: 'readonly', handleFormResponse: 'readonly',
    getPayloadFromScripts: 'readonly', getForumPayload: 'readonly',
    postDecensuredMessageToJvc: 'readonly', extractMessageId: 'readonly',
    performRedirection: 'readonly', saveToDecensuredApi: 'readonly',
    createTopicAndMessage: 'readonly', processNewTopicCreation: 'readonly',
    handleTopicDecensuredCreationFlow: 'readonly', triggerNativeTopicCreation: 'readonly',
    handleDecensuredTopicCreation: 'readonly',
    // decensured-main.js
    initDecensuredPing: 'readonly', initDecensured: 'readonly',
    // settings.js
    buildTooltip: 'readonly', buildSettingsPage: 'readonly', addChangeLogEvent: 'readonly',
    fetchChangelog: 'readonly', addToggleEvent: 'readonly', addRangeEvent: 'readonly',
    addSelectEvent: 'readonly', addSettingEvents: 'readonly', addPrebouclesEvents: 'readonly',
    addSortEvent: 'readonly', addImportExportEvent: 'readonly', addCollapsibleEvents: 'readonly',
    buildPrebouclesTable: 'readonly', buildSettingEntities: 'readonly',
    writeEntityKeys: 'readonly', refreshSubjectKeys: 'readonly', refreshAuthorKeys: 'readonly',
    refreshTopicIdKeys: 'readonly', keyIsAllowed: 'readonly', createAddEntityEvent: 'readonly',
    createSearchEntitiesEvent: 'readonly', refreshEntityCounts: 'readonly',
    refreshCollapsibleContentHeight: 'readonly', addSettingButton: 'readonly',
    addSearchFilterToggle: 'readonly', addDisableFilteringButton: 'readonly',
    showSettings: 'readonly', hideSettings: 'readonly', clearEntityInputs: 'readonly',
    clearSearchInputs: 'readonly', buildSettingLinkButton: 'readonly',
    addClearListButton: 'readonly', addHighlightModeratedButton: 'readonly',
    highlightModeratedTopics: 'readonly', forceApiDataRefresh: 'readonly',
    // privatemessages.js
    findPrivateMessageDefaultParams: 'readonly', sendPrivateMessagesToSpam: 'readonly',
    getPrivateMessageAuthor: 'readonly',
    // profile.js
    buildJvArchiveProfilButton: 'readonly', updateFilteredAuthorHeader: 'readonly',
    toggleFilteredTopicAuthor: 'readonly', updateFilteredMessages: 'readonly',
    buildFilterAuthorMessageButton: 'readonly', buildProfileBlacklistBadges: 'readonly',
    buildProfileLinkElements: 'readonly', buildProfileMedals: 'readonly',
    buildBlocProfile: 'readonly', createNewColLg6: 'readonly', getProfileColumnBlocs: 'readonly',
    buildProfileStats: 'readonly', buildProfileHistory: 'readonly',
    showDeletedMessages: 'readonly', getAuthorAvatarUrl: 'readonly',
    // extras.js
    buildSponsor: 'readonly', buildSupport: 'readonly', displaySecret: 'readonly',
    displayAnnouncement: 'readonly', buildExtras: 'readonly',
    // main.js
    getCurrentScriptVersion: 'readonly', suggestUpdate: 'readonly', filteringIsDisabled: 'readonly',
    getUserPseudo: 'readonly', getForumId: 'readonly', sendFinalEvent: 'readonly',
    getEntityTitle: 'readonly', getEntityRegex: 'readonly', toggleDeboucledDarkTheme: 'readonly',
    addSvgs: 'readonly', enableMobileZoom: 'readonly', getCurrentPageType: 'readonly',
    buildTopicNewPageUri: 'readonly', getTopicPageContent: 'readonly',
    getForumPageContent: 'readonly', handlePendingMessageQuotes: 'readonly',
    handleTopicList: 'readonly', handleTopicListOptions: 'readonly',
    parseTopicListAuthors: 'readonly', handleHotTopics: 'readonly', handlePoc: 'readonly',
    highlightBlacklistedAuthor: 'readonly', highlightBlacklistMatches: 'readonly',
    blacklistsIncludingEntity: 'readonly', handleMessageBlacklistMatches: 'readonly',
    hideMessageContent: 'readonly', handleBlSubjectIgnoreMessages: 'readonly',
    handleMessage: 'readonly', parseTopicAuthor: 'readonly', handleTopicWhitelist: 'readonly',
    highlightTopicHeaderTitle: 'readonly', buildTopicHeaderBadges: 'readonly',
    createTopicHeaderSmileys: 'readonly', handleTopicHeader: 'readonly',
    displayTopicDeboucledMessage: 'readonly', prepareTopicOptions: 'readonly',
    prepareMessageOptions: 'readonly', handleTopicMessages: 'readonly',
    handleSearch: 'readonly', handlePrivateMessage: 'readonly', handlePrivateMessages: 'readonly',
    buildBoucledAuthorButton: 'readonly', handleProfile: 'readonly',
    handlePrivateMessageNotifs: 'readonly', handleError: 'readonly', loadStyles: 'readonly',
    updateCurrentUser: 'readonly', getCurrentUserPseudo: 'readonly', init: 'readonly',
};

export default [
    js.configs.recommended,
    {
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'script',
            globals: {
                ...globals.browser,
                // Greasemonkey/Tampermonkey
                GMStorage: 'readonly', GM: 'readonly',
                GM_setValue: 'readonly', GM_getValue: 'readonly', GM_deleteValue: 'readonly',
                GM_listValues: 'readonly', GM_xmlhttpRequest: 'readonly', GM_openInTab: 'readonly',
                GM_notification: 'readonly', GM_setClipboard: 'readonly', GM_info: 'readonly',
                GM_getResourceURL: 'readonly', GM_getResourceText: 'readonly', GM_addStyle: 'readonly',
                GM_log: 'readonly', unsafeWindow: 'readonly',
                // Third-party libs
                TimeSpan: 'readonly', distance: 'readonly', Swal: 'readonly',
                InfiniteScroll: 'readonly', ShowMore: 'readonly', localforage: 'readonly',
                MouseEvent: 'readonly',
                // Cross-file project globals
                ...projectGlobals,
            }
        },
        rules: {
            'no-unused-vars': ['warn', { args: 'none', vars: 'local', varsIgnorePattern: '^_' }],
            'no-redeclare': 'off',
            'no-empty': ['warn', { allowEmptyCatch: true }],
            'no-constant-condition': ['error', { checkLoops: false }],
        }
    },
    // Config/build files that use ES modules
    {
        files: ['eslint.config.js', 'changelog-md.make.js'],
        languageOptions: {
            sourceType: 'module',
        }
    },
    {
        ignores: [
            'deboucled.debug.js',
            'deboucled.user.js',
            'deboucled.meta.js',
            'deboucled.meta.debug.js',
            'localforage-ttl.js',
            'node_modules/**',
            'version',
            '_resources/**',
            '_context/**',
        ]
    }
];
